### POST request to create patient
POST http://localhost:4000/patients/add
Content-Type: Application/json

{
  "name" : "Chandan Jaladi",
  "address": "3734 Copper Ln",
  "dateOfBirth": "2001-06-16",
  "email": "chandan@example.com",
  "registeredDate": "2025-07-26"
}

###